# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 15 Pro Max @ iOS 17.2",
  "iPhone 11 Pro Max @ iOS 17.2",
  "iPhone 8+ @ iOS 15.5",
  "iPad Pro 12.9\" 6gen @ iOS 17.2",
  "iPad Pro 12.9\" 2gen @ iOS 17.2",
])

languages([
  "de-DE",
  "en-US",
  "es-ES",
  "fr-FR",
  "uk",
  "ru",
])

# The name of the scheme which contains the UI Tests
scheme("Screenshots")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
# clear_previous_screenshots(true)

# Remove the '#' to set the status bar to 9:41 AM, and show full battery and reception. See also override_status_bar_arguments for custom options.
override_status_bar(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
# launch_arguments(["-favColor red"])

# For more information about all available options run
# fastlane action snapshot
